---
# NX_OS Upgrade switch

- name: Gather Facts
  nxos_facts:
    gather_subset: all
  register: facts

- name: Gather Current Version
  set_fact: currentver="{{ facts.ansible_facts['ansible_net_image'] }}"

- set_fact: newver='nxos.7.0.3.I7.6.bin'

- name: Instal New Version
  nxos_command:
      commands: install all nxos bootflash:nxos.7.0.3.I7.6.bin
  when: currentver != newver

- name: Reload Device
  ntc_reboot:
    platform: cisco_nxos_nxapi
    confirm: true
    timer: 2
  when: currentver != newver

- name: Verify Connectivity
  wait_for:
       port: 22
       timeout: 300
- nxos_command:
       commands: ping 10.65.254.1
       wait_for:
       – result[0] contains “!!!”
  register: result
  failed_when: “not ‘!!!’ in result.stdout[0]”

- name: Gather Facts After Upgrade
  nxos_facts:
    gather_subset: all
  register: facts2

- name: Gather New Current Version
  set_fact: newcurrentver="{{ facts.ansible_facts['ansible_net_image'] }}"

- name: Remove old Image
  nxos_config:
    commands: delete bootflash:///{{ currentver }}
  when: newcurrentver = newver

- name: Enable ISSU
  nxos_config:
      commands: boot mode lxc
  when: newcurrentver = newver

- name: Verify Connectivity
  wait_for:
       port: 22
       timeout: 300
- nxos_command:
       commands: ping 10.65.254.1
       wait_for:
       – result[0] contains “!!!”
  register: result
  failed_when: “not ‘!!!’ in result.stdout[0]”
#
